# AWS credentials
provider: 'aws'
aws_access_key_id: '<AWS_ACCESS_KEY_ID>'
aws_secret_key: '<AWS_SECRET_KEY>'
aws_region: '<AWS_REGION>'

# specify the volumes
volumes:
  vol-ebb71aa7:
    :lifetime: "<retention_time>"
    :host: "<hostname>"
    :type: "<frequency for taking snapshots>"
# Example
  vol-ebb71aa7:
    :lifetime: 1
    :host: "blah.foo.com"
    :type: "hourly" # you can specify daily as well 
