provider: 'aws'
aws_access_key_id: 'AKIAIXBGSOFRUNRSLULA'
aws_secret_key: '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'
aws_region: 'us-east-1'
volumes:
  vol-cbc14d87:
    :lifetime: '5d'
    :host: 'es01s.insideview.com'
    :type: 'daily'
  vol-b174b0f8:
    :lifetime: '5d'
    :host: 'es02s.insideview.com'
    :type: 'daily'
  vol-0813064a:
    :lifetime: '5d'
    :host: 'es02s.insideview.com'
    :type: 'daily'
